#!/usr/bin/env bash


alias ga='git add'
alias gb='git branch'
alias gbd='git branch -D'
alias gbrr='git branch -a | grep ">"'
alias gc='git commit'
alias gcl='git clone'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gdc='git diff --cached'
alias glast='git log -1 --color --decorate'
alias glog='git log --color --graph --decorate'
alias gmt='git mergetool'
alias gpull='git pull'
alias gpush='git push'
alias gr='git rm'
alias grebase='git pull --rebase'
alias greset='git reset --hard HEAD'
alias grv='git remote -v'
alias gst='git status'
alias gstsb='git status -sb'
alias gtag='git tag'
